### ISSUE TITLE
localhost failure - K8 failure adding label to proxy node

### ISSUE THREAD

**Issue by hjohnso4** [ibm-cloud-architecture/refarch-privatecloud#15]
Hello

After following the instructions, the ICP installation goes well until:

TASK [config-k8s-nodes : Adding label to master nodes] *************************
changed: [localhost] => (item=172.31.62.172)

TASK [config-k8s-nodes : Adding label to proxy nodes] **************************
failed: 

172.31.57.77               : ok=116  changed=35   unreachable=0    failed=0
172.31.60.100              : ok=116  changed=35   unreachable=0    failed=0
172.31.62.172              : ok=175  changed=54   unreachable=0    failed=0
172.31.63.35               : ok=116  changed=35   unreachable=0    failed=0
172.31.63.55               : ok=116  changed=35   unreachable=0    failed=0
localhost                  : ok=75   changed=12   unreachable=0    failed=1

![image](https://user-images.githubusercontent.com/18459908/35935787-c31ed50c-0c41-11e8-8185-1bd1bae76f00.png)

I am not sure why this is happening.  I can SSH and ping all nodes.  All IP addresses are correct in the /etc/hosts

![image](https://user-images.githubusercontent.com/18459908/35936259-01bc5856-0c43-11e8-994a-c9ec65a17c07.png)

Thank you

**Comment by VictorHavard** [comment]
This is normally because of either not enough RAM for all of the containers to start or a networking issue.  Make sure all the /etc/hosts files are correct and the same.  It looks like this is on an AWS instance, so make sure all ports are open between the nods on the firewall and that you have opened ports 8001, 4001, 8500, 8443, and 9443 are open on the external IPs.

**Comment by VictorHavard** [comment]
Closing old ticket which should have been closed long ago.
