### ISSUE TITLE
ICP 3.1.0 EE install on Ubuntu 16.04 fails at auth-pdp intialization

### ISSUE THREAD

**Issue by zaheershaffi2018** [ibm-cloud-architecture/refarch-privatecloud#24]
We are having issue in deploying the ICP over docker on master , during installation we are having below error.
FAILED - RETRYING: Waiting for auth-pdp to start (100 retries left).
FAILED - RETRYING: Waiting for auth-pdp to start (99 retries left).
FAILED - RETRYING: Waiting for auth-pdp to start (98 retries left).
FAILED - RETRYING: Waiting for auth-pdp to start (97 retries left).
FAILED - RETRYING: Waiting for auth-pdp to start (96 retries left).

and in logs we are getting the below error, will you please help us out in this issue ?
![docker1](https://user-images.githubusercontent.com/43265091/50344370-83e53200-054c-11e9-8d88-5535f0ca0cd5.png)
![docker2](https://user-images.githubusercontent.com/43265091/50344371-83e53200-054c-11e9-999e-4f0b24b6da24.png)

**Comment by bmarolleau** [comment]
Hi, don't know if you already solved your issue. 
I experienced the same pb when I tried to install ICP 3.1.1 (boot= Ubuntu 18.10 ppc64le | master,mgt,worker=Ubuntu 18.10 ppc64le) .  Exactly the same effect, crashloopbackoff, with psp error. 
After hundreds tentatives, manual cleanup etc.  I run the inception uninstall , then inception install. and it worked!  no more psp error, certs error, API server error...

**Comment by zaheershaffi2018** [comment]
> Hi, don't know if you already solved your issue.
> I experienced the same pb when I tried to install ICP 3.1.1 (boot= Ubuntu 18.10 ppc64le | master,mgt,worker=Ubuntu 18.10 ppc64le) . Exactly the same effect, crashloopbackoff, with psp error.
> After hundreds tentatives, manual cleanup etc. I run the inception uninstall , then inception install. and it worked! no more psp error, certs error, API server error...

hey bmarolleau , thank you for quick response, can you please let me confirm that should I run the same install command with uninstall parameter or there is some other way around for uninstalling the icp ?

**Comment by bmarolleau** [comment]
Hi, well I'm just an ICP user, not an advanced support guy :) but I just used
`docker run --net=host -t -e LICENSE=accept -v "$(pwd)":/installer/cluster ibmcom/icp-inception-ppc64le:3.1.1-ee uninstall -vv`
`/docker run --net=host -t -e LICENSE=accept -v "$(pwd)":/installer/cluster ibmcom/icp-inception-ppc64le:3.1.1-ee install -vv  `
please adapt to your architecture for inception image name.  good luck!

**Comment by VictorHavard** [comment]
This is not an error unless all 100 retries fail and the installation fails.  What is happening here is, the installer is pulling all the needed container images, installing them, waiting for them to come up, and then configuring them.  The installer kicks off the process and then tries every 60 seconds or so to see if it has completed yet.  If it has not, then it will print out that failure message, decrement it's counter, and try again.  It will continue doing this until it eventually responds and the installer continues, or it exhausts its retries and the installation fails.

Most likely the reason your uninstall and re-install worked is because the images were already pulled and it didn't need to pull them again and so it took less time for the overall process to complete the second time.

Just wait for the process to complete.  If it fails after all 100 retries then you have something else going on - could be a firewall issue (needed ports are not open) or a storage issue (out of disk space).

**Comment by VictorHavard** [comment]
ICP documentation is now obsolete.  Closing issue.
